// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package ratelimit

import caches "github.com/npxcomplete/caches/src"

func NewStringSwcbLRUCache(capacity int) privateStringSwcbLRUCache {
	return privateStringSwcbLRUCache{generic: caches.NewLRUCache(capacity)}
}

func WrapStringSwcbCache(cache caches.Interface) privateStringSwcbLRUCache {
	return privateStringSwcbLRUCache{generic: cache}
}

// genny is case sensitive even though this has other meanings in go, so we prefix the intent.
type privateStringSwcbLRUCache struct {
	generic caches.Interface
}

// see caches.Interface for contract
func (cache privateStringSwcbLRUCache) Put(key string, value *swcb) *swcb {
	result, _ := cache.generic.Put(key, value).(*swcb)
	return result
}

// see caches.Interface for contract
func (cache privateStringSwcbLRUCache) Get(key string) (result *swcb, err error) {
	value, err := cache.generic.Get(key)
	result, _ = value.(*swcb)
	return
}
